# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cohj9fis6-capi-aws
  namespace: cohj9fis6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cohj9fis6-capi-aws
subjects:
- kind: ServiceAccount
  name: cohj9fis6-capi-aws
